draw_config:
  separate_combo_diagrams: false
  outer_pad_h: 60
  arc_radius: 6

parse_config:
  zmk_combos:
    less_than:     { align: top, offset: 0.0 }
    bracket_left:  { align: bottom, offset: 0.0 }
    bracket_right: { align: bottom, offset: 0.0 }
    bigger_than:   { align: top, offset: 0.0 }
    astrsk:        { align: top, offset: 0.8 }
    plus:          { align: bottom, offset: 0.8 }
    tilde:             { align: top, offset: 0.0 }
    grave:             { align: top, offset: 0.0 }
    parentheses_left:  { align: bottom, offset: 0.0 }
    parentheses_right: { align: bottom, offset: 0.0 }
    colon:             { align: top, offset: 0.0 }
    ampersand: { align: top, offset: 0.2 }
    equal:     { align: top, offset: 0.8 }
    dollar:    { align: bottom, offset: 1.0 }
    Pipe:        { align: bottom, offset: 0.0 }
    brace_left:  { align: top, offset: 0.0 }
    brace_right: { align: top, offset: 0.0 }
    semcol:      { align: bottom, offset: 0.0 }
    underscore: { align: bottom, offset: 0.2 }
    minus:      { align: top, offset: 0.8 }
    excl:       { align: bottom, offset: 1.0 }
    cpslck: { align: top, offset: 1.5 }